export const SAVE_BETS_OF_CART = 'SAVE_BETS_OF_CART';
export const SAVE_DATA_OF_USER = 'SAVE_DATA_OF_USER';
export const SAVE_GAMES =   'SAVE_BETS_OF_CART';
export const DELETE_BET_OF_CART = 'DELETE_BET_OF_CART';
export const ERASE_BETS_OF_USER = 'ERASE_BETS_OF_USER';
